services:
  - type: web
    name: questedge-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py makemigrations
      python manage.py migrate
startCommand: python manage.py migrate && gunicorn myproject.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        value: your-secret-key
      - key: ALLOWED_HOSTS
        value: questedge-backend.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://questedge-backend.onrender.com
