# Generated by Django 5.2.1 on 2025-05-28 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='auth_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts_direct', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='auth_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='aptitude_marks',
            field=models.IntegerField(help_text='Aptitude marks'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='technical_marks',
            field=models.IntegerField(help_text='Technical marks'),
        ),
    ]
