# Generated by Django 5.2.1 on 2025-06-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_attempt_auth_user_id_userdetail_auth_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='marks',
            field=models.IntegerField(blank=True, help_text='Total marks (auto-calculated)', null=True),
        ),
    ]
