# Generated by Django 5.2.1 on 2025-06-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_attempt_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='avg_aptitude_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='avg_technical_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='total_score',
            field=models.FloatField(default=0),
        ),
    ]
