# Generated by Django 5.2.1 on 2025-06-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_userdetail_avg_aptitude_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='category',
            field=models.CharField(default='general', help_text='Category of the attempt', max_length=50),
        ),
    ]
