# Generated by Django 5.2.1 on 2025-06-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_attempt_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
