# Generated by Django 5.2.1 on 2025-06-13 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
