# Generated by Django 5.2.1 on 2025-06-30 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_delete_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='myapp.room'),
        ),
    ]
