# Generated by Django 5.2.1 on 2025-06-30 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_attempt_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='room',
        ),
    ]
